### PR TITLE
Added [ Object.keys/values/entries ] > es6

### PR DESCRIPTION
**Pull request by vipulrawat**
Three additional methods `Object.keys(), Object.values(), Object.keys()` to es6 are added. These methods are very useful when handling JSON and large object files in the program.

### CODE REVIEW

**Comment by leon-good-life** [comment]
Thank you for the PR. I will build and deploy soon.

**Comment by leon-good-life** [comment]
@vipulrawat Your es6 example is now on the website. Thanks for your contribution. 
I just made your comments multiline to avoid long (and non visible) code lines on mobile devices.

**Comment by leon-good-life** [comment]
@vipulrawat I'm very happy that there are contributors. There is a credit under the example. And in README.md file.

**Comment by vipulrawat** [comment]
@leon-good-life Thanks. I'll be contributing some more useful snippets in the future. :)

**Pull request merged**
